export const TEXT = {
  app: {
    brand: "Moa",
    title: "로컬 노트",
  },
  actions: {
    clearFilters: "필터 지우기",
    delete: "삭제",
    newDocument: "새 문서",
    rebuildIndex: "인덱스 다시 만들기",
    saveNow: "지금 저장",
    useVault: "보관함 사용",
  },
  aria: {
    document: "문서",
    editor: "편집기",
    hideSearchDetails: "검색 상세 숨기기",
    library: "라이브러리",
    markdownSource: "마크다운 원문",
    mode: "모드",
    panel: "패널",
    searchAndFilters: "검색 및 필터",
    searchSort: "검색 정렬",
    showSearchDetails: "검색 상세 보이기",
    vaultPath: "보관함 경로",
  },
  confirm: {
    moveToTrash: (title: string) => `"${title}" 문서를 로컬 휴지통으로 이동할까요?`,
  },
  defaults: {
    newDocumentBody: "# 제목 없음\n\n여기에 내용을 작성하세요.",
    newDocumentTitle: "제목 없음",
  },
  empty: {
    documentListBody: "노트를 만들거나 현재 필터를 지워보세요.",
    documentListTitle: "문서가 없습니다",
    documentPanelBody: "새 마크다운 문서를 만들거나 목록에서 문서를 선택하세요.",
    documentPanelTitle: "선택된 문서가 없습니다",
  },
  labels: {
    documents: "문서",
    issues: "문제",
    modified: "수정일",
    notes: "노트",
    panelDocuments: "문서",
    panelSettings: "설정",
    relevance: "관련도",
    search: "검색",
    sqliteIndex: "SQLite 인덱스",
    tag: "태그",
    tags: "태그",
    title: "제목",
    vault: "보관함",
    viewEdit: "편집",
    viewRead: "보기",
  },
  issueKinds: {
    duplicateDocumentId: "중복 문서 ID",
    invalidDocument: "잘못된 문서",
  },
  messages: {
    documentCreated: "문서를 만들었습니다.",
    documentMovedToTrash: "문서를 휴지통으로 이동했습니다.",
    indexRebuilt: "마크다운 파일에서 인덱스를 다시 만들었습니다.",
    vaultLoaded: "보관함을 불러왔습니다.",
  },
  placeholders: {
    all: "전체",
    search: "제목, 본문, 태그",
    tags: "쉼표로 구분한 태그",
    vaultPath: "보관함 경로",
  },
  saveState: {
    dirty: "저장 안 됨",
    error: "저장 실패",
    idle: "준비됨",
    saved: "저장됨",
    saving: "저장 중",
  },
  state: {
    detailsClosed: "상세",
    detailsOpen: "숨기기",
    loading: "불러오는 중...",
    loadingVault: "보관함을 불러오는 중...",
    notAvailable: "-",
    rebuilding: "다시 만드는 중...",
  },
} as const;
